// seed.js — Run with: node seed.js
// Seeds D1 database with all products, promo codes, and flash sales
// Requires: wrangler CLI authenticated, D1 database created

const { execSync } = require('child_process');

const DB_NAME = 'unicenutra-db';

const products = [
  // ===== Cardiovascular & Circulatory Support =====
  { name_en:"Triple Strength Omega-3 Fish Oil", name_sw:"Mafuta ya Samaki Omega-3 Ulimwengu", name_fr:"Huile de Poisson Oméga-3 Triple Force", category:"cardiovascular", price:3500, original_price:null, unit_en:"90 softgels", unit_sw:"Vidonge 90", unit_fr:"90 gélules", image_url:"assets/products/01-omega3-fish-oil.webp", stock:30, rating:4.8, review_count:22, badges:["Bestseller"], desc_en:"Highly concentrated essential fatty acids supplying structural EPA and DHA. Maintains vascular elasticity, manages systemic inflammation, lowers triglycerides, and supports cognitive health.", desc_sw:"Asidi fatty muhimu zenye umakini mkubwa zinazotoa EPA na DHA. Zinadumisha uhimilivu wa mishipa, kusawazisha mfumo wa uvimbe, kupunguza triglycerides, na kuunga mkono afya ya ubongo.", desc_fr:"Acides gras essentiels hautement concentrés fournissant de l'EPA et du DHA structurels. Maintiennent l'élasticité vasculaire, gèrent l'inflammation systémique, réduisent les triglycérides et soutiennent la santé cognitive.", benefits_en:'["Maintains vascular elasticity","Reduces systemic inflammation","Lowers triglyceride levels","Supports cognitive health"]', benefits_sw:'["Inadumisha uhimilivu wa mishipa","Inapunguza mfumo wa uvimbe","Inapunguza viwango vya triglyceride","Inaunga mkono afya ya ubongo"]', benefits_fr:'["Maintient l\'élasticité vasculaire","Réduit l\'inflammation systémique","Abaisse les triglycérides","Soutient la santé cognitive"]', sort_order:1 },
  { name_en:"Aged Garlic Extract", name_sw:"Mwanzo wa Gesi Iliondolewa", name_fr:"Extrait d'Ail Vieilli", category:"cardiovascular", price:2800, original_price:null, unit_en:"60 capsules", unit_sw:"Vidonge 60", unit_fr:"60 gélules", image_url:"assets/products/02-aged-garlic-extract.webp", stock:25, rating:4.7, review_count:18, badges:[], desc_en:"An odorless, fermented garlic formulation containing active organosulfur components. Optimizes arterial blood pressure, manages healthy cholesterol profiles, and delivers foundational microbial defenses.", desc_sw:"Mchanganyiko wa gesi usio na harufu, uliochongwa, unaosherehekea viungo vya organosulfur. Inaboresha shinikizo la damu ya mishipa, kusawazisha viwango vya cholesterol, na kutoa ulinzi wa msingi wa vijidudu.", desc_fr:"Formulation d'ail fermenté inodore contenant des composés organosoufre actifs. Optimise la pression artérielle, gère les profils de cholestérol sains et fournit des défenses microbiennes fondamentales.", benefits_en:'["Optimizes arterial blood pressure","Manages healthy cholesterol profiles","Odorless fermented formulation","Delivers microbial defenses"]', benefits_sw:'["Inaboresha shinikizo la damu ya mishipa","Inasawazisha viwango vya cholesterol","Mchanganyiko usio na harufu","Inatoa ulinzi wa vijidudu"]', benefits_fr:'["Optimise la pression artérielle","Gère les profils de cholestérol sains","Formulation fermentée inodore","Fournit des défenses microbiennes"]', sort_order:2 },
  { name_en:"Blood Circulation Flow", name_sw:"Mtiririko wa Mzunguko wa Damu", name_fr:"Circulation Sanguine", category:"cardiovascular", price:2200, original_price:null, unit_en:"60 tablets", unit_sw:"Vidonge 60", unit_fr:"60 comprimés", image_url:"assets/products/03-blood-circulation-flow.webp", stock:20, rating:4.6, review_count:15, badges:[], desc_en:"A targeted nutrient and herbal botanical blend designed to promote efficient vascular hemodynamics. Strengthens vein walls and reduces fluid pooling or heaviness in the lower extremities.", desc_sw:"Mchanganyiko wa virutubisho na mimea yaliyolengwa iliyoundwa kuendeleza mfumo wa damu. Inaimarisha kuta za mishipa na kupunguza maji kwenye viungo vya chini.", desc_fr:"Mélange ciblé de nutriments et de plantes botaniques conçu pour promouvoir une hémodynamique vasculaire efficace. Renforce les parois veineuses et réduit la stagnation fluidique.", benefits_en:'["Promotes vascular hemodynamics","Strengthens vein walls","Reduces fluid pooling","Targets lower extremities"]', benefits_sw:'["Inaendeleza mfumo wa damu wa mishipa","Inaimarisha kuta za mishipa","Inapunguza maji kwenye viungo","Inalenga viungo vya chini"]', benefits_fr:'["Promeut l\'hémodynamique vasculaire","Renforce les parois veineuses","Réduit la stagnation fluidique","Cible les membres inférieurs"]', sort_order:3 },
  { name_en:"Dried Hawthorn Berries", name_sw:"Tunda la Hawthorn Kavu", name_fr:"Baies d'Aubépine Séchées", category:"cardiovascular", price:1800, original_price:null, unit_en:"100g loose", unit_sw:"100g huru", unit_fr:"100g en vrac", image_url:"assets/products/04-dried-hawthorn-berries.webp", stock:18, rating:4.5, review_count:10, badges:[], desc_en:"Dehydrated, sliced whole-food berries used traditionally as an infusion or tea. Naturally enhances cardiac muscle contraction efficiency, helps regulate blood pressure, and provides potent antioxidant flavonoids.", desc_sw:"Matunda yaliyokaushwa, yaliyokatwa kikamilifu, yatumika kwa jadi kama infusioni au chai. Inaongeza ufanisi wa kusinywa kwa misa ya moyo, kusaidia kusawazisha shinikizo la damu, na kutoa flavonoids za antioxidants.", desc_fr:"Baies entières déshydratées et tranchées utilisées traditionnellement en infusion ou en thé. Améliore naturellement l'efficacité de la contraction du muscle cardiaque, aide à réguler la pression artérielle et fournit des flavonoïdes antioxydants puissants.", benefits_en:'["Enhances cardiac contraction","Regulates blood pressure","Rich in antioxidant flavonoids","Traditional whole-food infusion"]', benefits_sw:'["Inaongeza ufanisi wa kusinywa kwa misa ya moyo","Inasawazisha shinikizo la damu","Yenye flavonoids nyingi za antioxidants","Infusioni ya jadi ya matunda kamili"]', benefits_fr:'["Améliore la contraction cardiaque","Régule la pression artérielle","Riche en flavonoïdes antioxydants","Infusion traditionnelle à base de baies entières"]', sort_order:4 },
  // ===== Cellular Defense & Metabolic Regulators =====
  { name_en:"N-Acetyl Cysteine (NAC)", name_sw:"N-Acetyl Cysteine (NAC)", name_fr:"N-Acétyl Cystéine (NAC)", category:"cellular", price:2500, original_price:null, unit_en:"60 capsules", unit_sw:"Vidonge 60", unit_fr:"60 gélules", image_url:"assets/products/05-nac.webp", stock:22, rating:4.8, review_count:16, badges:["Popular"], desc_en:"A stable sulfur-bearing amino acid that serves as the immediate direct precursor to glutathione. Drives hepatic detoxification pathways, neutralizes heavy metal accumulation, and thins thick respiratory mucus.", desc_sw:"Asidi amino thabati yenye kiberiti inayotumika kuwa mtangulizi wa moja kwa moja wa glutathione. Inaendesha njia za kusafisha ini, kutengeneza uzito wa chuma, na kufanya mucus ya kupumua kuwa nyeposi.", desc_fr:"Acide aminé soufré stable servant de précurseur direct immédiat au glutathion. Oriente les voies de détoxification hépatique, neutralise l'accumulation de métaux lourds et fluidifie le mucus respiratoire épais.", benefits_en:'["Precursor to glutathione synthesis","Drives hepatic detoxification","Neutralizes heavy metal accumulation","Thins respiratory mucus"]', benefits_sw:'["Mtangulizi wa glutathione","Inaendesha njia za kusafisha ini","Inatengeneza uzito wa chuma","Inafanya mucus ya kupumua kuwa nyeposi"]', benefits_fr:'["Précurseur de la synthèse du glutathion","Oriente la détoxification hépatique","Neutralise l\'accumulation de métaux lourds","Fluidifie le mucus respiratoire"]', sort_order:5 },
  { name_en:"Selenium 200mcg", name_sw:"Selenium 200mcg", name_fr:"Sélénium 200mcg", category:"cellular", price:1500, original_price:null, unit_en:"60 tablets", unit_sw:"Vidonge 60", unit_fr:"60 comprimés", image_url:"assets/products/06-selenium.webp", stock:28, rating:4.7, review_count:12, badges:[], desc_en:"An essential trace mineral acting as a crucial cofactor for the enzyme glutathione peroxidase. Directly protects cells against oxidative damage, maintains thyroid hormone conversions, and primes immune response cycles.", desc_sw:"Madini muhimu yanayotumika kuwa msaidizi muhimu wa enzyme ya glutathione peroxidase. Inalinda seli dhidi ya uharibifu wa oksidishaji, kusawazisha mabadiliko ya homoni za甲状腺, na kuandaa mizunguko ya mwitikio wa kinga.", desc_fr:"Oligo-élément essentiel agissant comme cofacteur crucial pour l'enzyme glutathion peroxydase. Protège directement les cellules contre les dommages oxydatifs, maintient les conversions hormonales thyroïdiennes et prépare les cycles de réponse immunitaire.", benefits_en:'["Cofactor for glutathione peroxidase","Protects cells from oxidative damage","Maintains thyroid hormone conversions","Primes immune response cycles"]', benefits_sw:'["Msaidizi wa glutathione peroxidase","Inalinda seli dhidi ya uharibifu","Kusawazisha mabadiliko ya homoni za thyroid","Kuandaa mizunguko ya mwitikio wa kinga"]', benefits_fr:'["Cofacteur pour glutathion peroxydase","Protège les cellules des dommages oxydatifs","Maintient les conversions hormonales thyroïdiennes","Prépare les cycles de réponse immunitaire"]', sort_order:6 },
  { name_en:"Sugar Balance & Chromium Picolinate", name_sw:"Usawa wa Sukari na Chromium Picolinate", name_fr:"Équilibre Sucre & Picolinate de Chrome", category:"cellular", price:2800, original_price:null, unit_en:"60 capsules", unit_sw:"Vidonge 60", unit_fr:"60 gélules", image_url:"assets/products/07-sugar-balance.webp", stock:20, rating:4.6, review_count:14, badges:[], desc_en:"A synergy of trace minerals and active bitter herbs formulated to modulate peripheral insulin receptor sensitivity. Assists the body in processing dietary carbohydrates and stabilizes fluctuating blood glucose curves.", desc_sw:"Umoja wa madini midogo na mimea chungu hai iliyoundwa kurekebisha unyeti wa receptors za insulini. Inasaidia mwili kuchakata carbs za chakula na kusawazisha viwango vya glucose vya damu.", desc_fr:"Synergie d'oligo-éléments et d'herbes amères actives formulée pour moduler la sensibilité des récepteurs insuliniques périphériques. Aide le corps à traiter les glucides alimentaires et stabilise les courbes glycémiques fluctuantes.", benefits_en:'["Modulates insulin receptor sensitivity","Assists carbohydrate processing","Stabilizes blood glucose curves","Trace mineral synergy"]', benefits_sw:'["Kurekebisha unyeti wa receptors za insulini","Kusaidia uchakataji wa carbs","Kusawazisha viwango vya glucose","Umoja wa madini midogo"]', benefits_fr:'["Module la sensibilité des récepteurs insuliniques","Aide au traitement des glucides","Stabilise les courbes glycémiques","Synergie d\'oligo-éléments"]', sort_order:7 },
  // ===== Skeletal Structure & Essential Minerals =====
  { name_en:"Calcium Magnesium Zinc + D3", name_sw:"Calcium Magnesium Zinc + D3", name_fr:"Calcium Magnésium Zinc + D3", category:"skeletal", price:2200, original_price:null, unit_en:"120 tablets", unit_sw:"Vidonge 120", unit_fr:"120 comprimés", image_url:"assets/products/08-cal-mag-zinc-d3.webp", stock:25, rating:4.7, review_count:20, badges:["Popular"], desc_en:"A structural multi-mineral matrix reinforced with fat-soluble vitamin D3. Optimizes bone mineralization, regulates muscular contraction-relaxation cycles, and sustains cellular immune actions.", desc_sw:"Matriks ya madini mingi iliyoimarishwa na vitamini D3 yenye mafuta. Inaboresha usanisinuru wa mifupa, kusawazisha mizunguko ya kusinywa-kulegea kwa misa, na kuendeleza vitendo vya kinga vya seli.", desc_fr:"Matrice multi-minérale structurelle renforcée par la vitamine D3 liposoluble. Optimise la minéralisation osseuse, régule les cycles de contraction-relaxation musculaire et maintient les actions immunitaires cellulaires.", benefits_en:'["Optimizes bone mineralization","Reinforced with vitamin D3","Regulates muscle contraction cycles","Sustains cellular immune actions"]', benefits_sw:'["Inaboresha usanisinuru wa mifupa","Imeimarishwa na vitamini D3","Kusawazisha mizunguko ya kusinywa kwa misa","Kuendeleza vitendo vya kinga vya seli"]', benefits_fr:'["Optimise la minéralisation osseuse","Renforcée avec la vitamine D3","Régule les cycles de contraction musculaire","Maintient les actions immunitaires cellulaires"]', sort_order:8 },
  { name_en:"Triple Magnesium Complex", name_sw:"Magnesium Complex ya Mara Tatu", name_fr:"Complexe Magnésium Triple", category:"skeletal", price:2400, original_price:null, unit_en:"60 capsules", unit_sw:"Vidonge 60", unit_fr:"60 gélules", image_url:"assets/products/09-triple-magnesium.webp", stock:22, rating:4.8, review_count:16, badges:[], desc_en:"A combined formulation containing multiple bioavailable delivery vectors of elemental magnesium. Works deeply to soothe neuromuscular hyperactivity, ease muscle cramps, and promote deep nervous system relaxation.", desc_sw:"Mchanganyiko unaovecta za uwasilishaji nyingi za magnesium ya elementi. Inafanya kazi kwa kina kupunguza shughuli nyingi za neuromuscular, kulegea krama za misa, na kukuza upole wa mfumo wa neva.", desc_fr:"Formulation combinée contenant plusieurs vecteurs de livrance bioavailables de magnésium élémentaire. Agit en profondeur pour apaiser l'hyperactivité neuromusculaire, soulager les crampes musculaires et favoriser la relaxation profonde du système nerveux.", benefits_en:'["Multiple bioavailable delivery vectors","Soothes neuromuscular hyperactivity","Eases muscle cramps","Promotes nervous system relaxation"]', benefits_sw:'["Za uwasilishaji nyingi za magnesium","Kupunguza shughuli za neuromuscular","Kulegea krama za misa","Kukuza upole wa mfumo wa neva"]', benefits_fr:'["Vecteurs de livrance bioavailables multiples","Apaise l\'hyperactivité neuromusculaire","Soulage les crampes musculaires","Favorise la relaxation du système nerveux"]', sort_order:9 },
  { name_en:"High Potency Zinc (50mg)", name_sw:"Zinc ya Uwiano wa Juu (50mg)", name_fr:"Zinc Haute Puissance (50mg)", category:"skeletal", price:1200, original_price:null, unit_en:"60 tablets", unit_sw:"Vidonge 60", unit_fr:"60 comprimés", image_url:"assets/products/10-zinc-50mg.webp", stock:30, rating:4.6, review_count:18, badges:["Bestseller"], desc_en:"An isolated trace mineral supplement serving as an enzymatic catalyst for hundreds of internal biological processes. Accelerates wound healing, builds T-lymphocytes, and blocks viral replication cycles.", desc_sw:"Madini madogo yaliyotengwa yanayotumika kuwa katalysti ya enzyme kwa mchakato wa biolojia ndani. Inaharakisha uponyaji vidonda, kujenga T-lymphocytes, na kuzuia mizunguko ya ulipukaji wa virusi.", desc_fr:"Supplément d'oligo-élément isolé servant de catalyseur enzymatique pour des centaines de processus biologiques internes. Accélère la cicatrisation des plaies, construit les lymphocytes T et bloque les cycles de réplication virale.", benefits_en:'["Enzymatic catalyst for biological processes","Accelerates wound healing","Builds T-lymphocytes","Blocks viral replication cycles"]', benefits_sw:'["Katalysti ya enzyme kwa mchakato wa biolojia","Kuharakisha uponyaji vidonda","Kujenga T-lymphocytes","Kuzuia mizunguko ya ulipukaji wa virusi"]', benefits_fr:'["Catalyseur enzymatique pour les processus biologiques","Accélère la cicatrisation des plaies","Construit les lymphocytes T","Bloque les cycles de réplication virale"]', sort_order:10 },
  // ===== Neurological & Stress Adaptogens =====
  { name_en:"Lion's Mane Liquid Extract", name_sw:"Mwanzo wa Maji ya Uzi wa Simba", name_fr:"Extrait Liquide Lion de la Mane", category:"neurological", price:4500, original_price:null, unit_en:"60ml tincture", unit_sw:"Dawa 60ml", unit_fr:"60ml teinture", image_url:"assets/products/11-lions-mane.webp", stock:15, rating:4.9, review_count:14, badges:["Premium"], desc_en:"A concentrated liquid extract from Hericium erinaceus fruiting bodies. Stimulates natural Neural Growth Factor (NGF) synthesis, enhancing memory retention, analytical focus, and myelin sheath structural integrity.", desc_sw:"Mwanzo wa maji uliokusanywa kutoka kwa matunda ya Hericium erinaceus. Inachochea utengenezaji wa Neural Growth Factor (NGF), kuboresha kumbukumbu, uchambuzi, na uhimilivu wa myelin sheath.", desc_fr:"Extrait liquide concentré provenant des fruiting bodies d'Hericium erinaceus. Stimule la synthèse naturelle du Neural Growth Factor (NGF), améliore la rétention mnésique, la concentration analytique et l'intégrité structurelle de la gaine de myéline.", benefits_en:'["Stimulates NGF synthesis","Enhances memory retention","Improves analytical focus","Supports myelin sheath integrity"]', benefits_sw:'["Inachochea utengenezaji wa NGF","Kuboresha kumbukumbu","Kuboresha uchambuzi","Kusaidia uhimilivu wa myelin sheath"]', benefits_fr:'["Stimule la synthèse du NGF","Améliore la rétention mnésique","Améliore la concentration analytique","Soutient l\'intégrité de la gaine de myéline"]', sort_order:11 },
  { name_en:"Rhodiola Rosea", name_sw:"Rhodiola Rosea", name_fr:"Rhodiola Rosea", category:"neurological", price:3200, original_price:null, unit_en:"60 capsules", unit_sw:"Vidonge 60", unit_fr:"60 gélules", image_url:"assets/products/12-rhodiola-rosea.webp", stock:18, rating:4.7, review_count:11, badges:[], desc_en:"A cold-climate adaptogenic root extract standardized for active rosavins and salidrosides. Helps the adrenal system balance sustained stress, mitigates mental burnout, and stabilizes physical performance.", desc_sw:"Mwanzo wa mizizi ya adaptogenic ya baridi uliochaguliwa kwa rosavins na salidrosides hai. Inasaidia mfumo wa adrenal kusawazisha msongo endelevu, kupunguza uchovu wa akili, na kusawazisha utendaji wa mwili.", desc_fr:"Extrait de racine adaptogène de climat froid standardisé pour les rosavins et salidroside actifs. Aide le système surrénal à équilibrer le stress soutenu, atténue l'épuisement mental et stabilise les performances physiques.", benefits_en:'["Standardized rosavins and salidrosides","Balances sustained stress","Mitigates mental burnout","Stabilizes physical performance"]', benefits_sw:'["Rosavins na salidrosides","Kusawazisha msongo endelevu","Kupunguza uchovu wa akili","Kusawazisha utendaji wa mwili"]', benefits_fr:'["Rosavins et salidroside standardisés","Équilibre le stress soutenu","Atténue l\'épuisement mental","Stabilise les performances physiques"]', sort_order:12 },
  { name_en:"Shilajit Complex", name_sw:"Mchanganyiko wa Shilajit", name_fr:"Complexe Shilajit", category:"neurological", price:5500, original_price:null, unit_en:"60 capsules", unit_sw:"Vidonge 60", unit_fr:"60 gélules", image_url:"assets/products/13-shilajit-complex.webp", stock:12, rating:4.8, review_count:9, badges:["Premium"], desc_en:"A mineral-dense fulvic acid resin compound combined with ashwagandha and ginseng roots. Facilitates direct mitochondrial ATP energy production, raises physical stamina, and combats long-term biological fatigue.", desc_sw:"Muundo wa asidi ya fulvic yenye madini mengi uliochanganywa na mizizi ya ashwagandha na ginseng. Inarahisisha utengenezaji wa ATP ya mitochondria, kuongeza ustahimilivu wa mwili, na kupigana na uchovu wa biolojia wa muda mrefu.", desc_fr:"Composé de résine d'acide fulvique riche en minéraux combiné avec des racines d'ashwagandha et de ginseng. Facilite la production directe d'ATP mitochondrial, augmente l'endurance physique et combat la fatigue biologique à long terme.", benefits_en:'["Facilitates mitochondrial ATP production","Combined with ashwagandha and ginseng","Raises physical stamina","Combats long-term fatigue"]', benefits_sw:'["Inarahisisha utengenezaji wa ATP ya mitochondria","Imechanganywa na ashwagandha na ginseng","Kuongeza ustahimilivu wa mwili","Kupigana na uchovu wa muda mrefu"]', benefits_fr:'["Facilite la production d\'ATP mitochondrial","Combiné avec ashwagandha et ginseng","Augmente l\'endurance physique","Combat la fatigue à long terme"]', sort_order:13 },
  // ===== Women's Health & Gut Microbiome =====
  { name_en:"Myo & D-Chiro Inositol", name_sw:"Myo & D-Chiro Inositol", name_fr:"Myo & D-Chiro Inositol", category:"womens", price:3800, original_price:null, unit_en:"60 sachets", unit_sw:"Mifuko 60", unit_fr:"60 sachets", image_url:"assets/products/14-inositol-40-1.webp", stock:16, rating:4.8, review_count:12, badges:["New"], desc_en:"A specialized carbohydrate isomer formulation prepared in a clinically validated 40:1 ratio. Primarily utilized to restore proper ovarian function, regulate menstrual timelines, and manage insulin dynamics in women with PCOS.", desc_sw:"Mchanganyiko wa carbohydrate isomer maalum uliotengenezwa kwa uwiano wa 40:1 uliothibitishwa kliniki. Unatumika hasa kurejesha utendaji sahihi wa ovari, kusawazisha muda wa hedhi, na kusawazisha dynamics za insulini kwa wanawake wenye PCOS.", desc_fr:"Formulation spécialisée d'isomères de glucides préparée dans un ratio 40:1 cliniquement validé. Utilisée principalement pour restaurer la fonction ovarienne appropriée, réguler les cycles menstruels et gérer la dynamique insulinique chez les femmes atteintes de SOPK.", benefits_en:'["Clinically validated 40:1 ratio","Restores ovarian function","Regulates menstrual timelines","Manages insulin dynamics in PCOS"]', benefits_sw:'["Uwiano wa 40:1 uliothibitishwa kliniki","Kurejesha utendaji wa ovari","Kusawazisha muda wa hedhi","Kusawazisha dynamics za insulini kwa PCOS"]', benefits_fr:'["Ratio 40:1 cliniquement validé","Restaure la fonction ovarienne","Régule les cycles menstruels","Gère la dynamique insulinique dans le SOPK"]', sort_order:14 },
  { name_en:"Women's Probiotic & Vaginal Health Gummies", name_sw:"Probiotic za Wanawake na Viatu vya Afya ya Vagina", name_fr:"Probiotiques Féminins & Pastilles Santé Vaginale", category:"womens", price:2600, original_price:null, unit_en:"60 gummies", unit_sw:"Viatu 60", unit_fr:"60 pastilles", image_url:"assets/products/15-womens-probiotic.webp", stock:18, rating:4.7, review_count:10, badges:["New"], desc_en:"Targeted, acid-resistant active bacterial strains delivering beneficial microbes to the reproductive tract. Prevents colonization of pathogenic bacteria and maintains a balanced internal pH environment.", desc_sw:"Aina za bakteria zilizolengwa, zinazostahimili asidi, zinazopeleka vijidudu vyenye manufaa kwa njia ya uzazi. Inazuia uenezi wa bakteria hatari na kudumisha mazingira ya pH ya ndani.", desc_fr:"Souches bactériennes actives ciblées, résistantes à l'acidité, délivrant des micro-organismes bénéfiques au tractus reproducteur. Prévient la colonisation de bactéries pathogènes et maintient un environnement pH interne équilibré.", benefits_en:'["Acid-resistant bacterial strains","Delivers beneficial microbes to reproductive tract","Prevents pathogenic colonization","Maintains balanced internal pH"]', benefits_sw:'["Aina za bakteria zinazostahimili asidi","Kupeleka vijidudu vyenye manufaa kwa njia ya uzazi","Kuzuia uenezi wa bakteria hatari","Kudumisha mazingira ya pH ya ndani"]', benefits_fr:'["Souches bactériennes résistantes à l\'acidité","Délivrent des micro-organismes bénéfiques au tractus reproducteur","Prévient la colonisation pathogène","Maintient un pH interne équilibré"]', sort_order:15 },
];

const promos = [
  { code:'WELCOME10', type:'percent', value:10, category:null, description:'10% off your order', min_order:0, max_uses:100 },
  { code:'HEART20', type:'category', value:20, category:'cardiovascular', description:'20% off cardiovascular supplements', min_order:0, max_uses:100 },
  { code:'FREESHIP', type:'freeship', value:0, category:null, description:'Free shipping', min_order:0, max_uses:200 },
  { code:'ADAPT15', type:'category', value:15, category:'neurological', description:'15% off adaptogens', min_order:0, max_uses:100 },
];

function escape(str) {
  return String(str).replace(/'/g, "''");
}

function buildProductSQL(p) {
  return `INSERT INTO products (name_en, name_sw, name_fr, category, price, original_price, unit_en, unit_sw, unit_fr, image_url, stock, rating, review_count, badges, desc_en, desc_sw, desc_fr, benefits_en, benefits_sw, benefits_fr, sort_order) VALUES ('${escape(p.name_en)}', '${escape(p.name_sw)}', '${escape(p.name_fr)}', '${escape(p.category)}', ${p.price}, ${p.original_price || 'NULL'}, '${escape(p.unit_en)}', '${escape(p.unit_sw)}', '${escape(p.unit_fr)}', '${escape(p.image_url)}', ${p.stock}, ${p.rating}, ${p.review_count}, '${escape(JSON.stringify(p.badges))}', '${escape(p.desc_en)}', '${escape(p.desc_sw)}', '${escape(p.desc_fr)}', '${escape(p.benefits_en)}', '${escape(p.benefits_sw)}', '${escape(p.benefits_fr)}', ${p.sort_order});`;
}

function buildPromoSQL(p) {
  return `INSERT INTO promos (code, type, value, category, description, min_order, max_uses) VALUES ('${escape(p.code)}', '${escape(p.type)}', ${p.value}, ${p.category ? `'${escape(p.category)}'` : 'NULL'}, '${escape(p.description)}', ${p.min_order}, ${p.max_uses});`;
}

// Build the full SQL
let sql = '-- U-NiceNutraCare Seed Data\n-- Generated by seed.js\n\n';

sql += '-- Products\n';
products.forEach(p => { sql += buildProductSQL(p) + '\n'; });

sql += '\n-- Promo Codes\n';
promos.forEach(p => { sql += buildPromoSQL(p) + '\n'; });

// Write to file
const fs = require('fs');
fs.writeFileSync('seed-data.sql', sql);
console.log('✅ Generated seed-data.sql with ' + products.length + ' products and ' + promos.length + ' promos');
console.log('\nTo seed your D1 database, run:');
console.log('  wrangler d1 execute unicenutra-db --file=./schema.sql');
console.log('  wrangler d1 execute unicenutra-db --file=./seed-data.sql');
