// seed.js — Run with: node seed.js
// Seeds D1 database with all products, promo codes, and flash sales
// Requires: wrangler CLI authenticated, D1 database created

import fs from 'fs';

const DB_NAME = 'unicenutra-db';

const products = [
  // ===== Supplements =====
  { name_en:"Wins Town Women's Probiotic Gummies (60 Gummies)", name_sw:"Viatu vya Probiotic za Wanawake Wins Town (Viatu 60)", name_fr:"Pastilles Probiotiques Féminines Wins Town (60 Pastilles)", category:"supplements", price:1590, original_price:2500, unit_en:"60 gummies", unit_sw:"Viatu 60", unit_fr:"60 pastilles", image_url:"assets/photoz/IMG-20260721-WA0149.jpg", stock:25, rating:4.7, review_count:18, badges:["Popular"], desc_en:"A chewable daily supplement formulated with 5 Billion CFUs of probiotics, prebiotics, D-mannose, and 100 mg of cranberry extract. Deliciously cranberry-flavored, these gummies support healthy vaginal pH, promote urinary tract function, and boost digestive immunity.", desc_sw:"Nyongeza ya kila siku inayotafunwa, iliyotengenezwa na CFU Bilioni 5 za probiotics, prebiotics, D-mannose, na extracts za cranberry 100 mg. Viatu hivi vinavyojaa ladha ya cranberry vinaunga mkono pH ya afya ya vagina, kukuza utendaji wa njia ya mkojo, na kuongeza kinga ya mmeng'enyo.", desc_fr:"Complément alimentaire quotidien mâchable formulé avec 5 milliards d'unités formant des colonies de probiotiques, prébiotiques, D-mannose et 100 mg d'extrait de canneberge. Délicieusement aromatisées à la canneberge, ces pastilles soutiennent un pH vaginal sain, favorisent la fonction urinaire et renforcent l'immunité digestive.", benefits_en:'["5 Billion CFU probiotics","Supports healthy vaginal pH","Promotes urinary tract function","Boosts digestive immunity"]', benefits_sw:'["Probiotics za CFU Bilioni 5","Zinaunga mkono pH ya afya ya vagina","Kukuza utendaji wa njia ya mkojo","Kuongeza kinga ya mmeng\'enyo"]', benefits_fr:'["5 milliards de CFU probiotiques","Soutient un pH vaginal sain","Favorise la fonction urinaire","Renforce l\'immunité digestive"]', sort_order:1 },
  { name_en:"Wins Town Collagen with Burn", name_sw:"Collagen ya Wins Town Pamoja na Burn", name_fr:"Collagène Wins Town avec Burn", category:"supplements", price:1250, original_price:3200, unit_en:"Powder supplement", unit_sw:"Nyongeza ya poda", unit_fr:"Complément en poudre", image_url:"assets/photoz/IMG-20260721-WA0159.jpg", stock:20, rating:4.6, review_count:12, badges:[], desc_en:"Dual-action wellness supplement powder combining multi-type collagen (Types I, II, III, V & X) with metabolism-boosting agents. Helps reduce visible cellulite, accelerate fat breakdown, and support skin elasticity, joint mobility, hair, and nails.", desc_sw:"Poda ya afya yenye vitendo viwili inayochanganya collagen ya aina nyingi (Aina I, II, III, V na X) pamoja na viungo vinavyoongeza metabolismi. Inasaidia kupunguza seluliti inayoonekana, kuharakisha uvunjaji wa mafuta, na kuunga mkono unyevu wa ngozi, uhamaji wa viungo, nywele, na kucha.", desc_fr:"Poudre de complément bien-être à double action combinant du collagène multi-types (Types I, II, III, V et X) avec des agents boosteurs de métabolisme. Aide à réduire la cellulite visible, accélérer la décomposition des graisses et soutenir l'élasticité de la peau, la mobilité articulaire, les cheveux et les ongles.", benefits_en:'["Multi-type collagen (I, II, III, V, X)","Reduces visible cellulite","Accelerates fat breakdown","Supports skin, joints, hair & nails"]', benefits_sw:'["Collagen ya aina nyingi (I, II, III, V, X)","Inapunguza seluliti inayoonekana","Kuharakisha uvunjaji wa mafuta","Kusaidia ngozi, viungo, nywele na kucha"]', benefits_fr:'["Collagène multi-types (I, II, III, V, X)","Réduit la cellulite visible","Accélère la décomposition des graisses","Soutient peau, articulations, cheveux & ongles"]', sort_order:2 },
  { name_en:"5D Gluta Collagen Glowing Powder (1 kg)", name_sw:"5D Gluta Collagen Glowing Powder (1 kg)", name_fr:"5D Gluta Collagen Poudre Éclat (1 kg)", category:"supplements", price:3290, original_price:4200, unit_en:"1 kg powder", unit_sw:"Poda 1 kg", unit_fr:"1 kg poudre", image_url:"assets/photoz/IMG-20260721-WA0160.jpg", stock:15, rating:4.8, review_count:14, badges:["Bestseller"], desc_en:"High-potency dietary supplement delivering 20g of grass-fed bovine collagen peptides alongside glutathione, hyaluronic acid, and vitamin C. Designed to brighten complexions, improve skin firming, and support hair, nail, and joint health from within.", desc_sw:"Nyongeza ya chakula yenye nguvu kubwa inayotoa collagen peptides 20g kutoka kwa ng'ombe waliolishwa kwa nyasi pamoja na glutathione, asidi ya hyaluronic, na vitamini C. Imetengenezwa kuboresha rangi ya ngozi, kuboresha uthabiti wa ngozi, na kuunga mkono afya ya nywele, kucha, na viungo.", desc_fr:"Complément alimentaire haute puissance délivrant 20g de peptides de collagène bovin nourri à l'herbe aux côtés de glutathion, d'acide hyaluronique et de vitamine C. Conçu pour éclaircir les teintes, améliorer la fermeté de la peau et soutenir la santé des cheveux, ongles et articulations de l'intérieur.", benefits_en:'["20g grass-fed bovine collagen","Glutathione & hyaluronic acid","Brightens complexion","Supports hair, nail & joint health"]', benefits_sw:'["Collagen peptides 20g za ng\'ombe","Glutathione na asidi ya hyaluronic","Kuboresha rangi ya ngozi","Kusaidia afya ya nywele, kucha na viungo"]', benefits_fr:'["20g collagène bovin nourri à l\'herbe","Glutathion & acide hyaluronique","Éclaircit le teint","Soutient santé cheveux, ongles & articulations"]', sort_order:3 },
  { name_en:"Duozi Marine Collagen+ 5-in-1", name_sw:"Duozi Marine Collagen+ 5-in-1", name_fr:"Duozi Marine Collagen+ 5-en-1", category:"supplements", price:2099, original_price:3200, unit_en:"Powder supplement", unit_sw:"Nyongeza ya poda", unit_fr:"Complément en poudre", image_url:"assets/photoz/IMG-20260721-WA0179.jpg", stock:18, rating:4.7, review_count:10, badges:["New"], desc_en:"A powdered dietary supplement containing marine collagen, biotin, vitamin C, melatonin, and hyaluronic acid for skin elasticity, hair/nail support, and anti-aging.", desc_sw:"Nyongeza ya chakula ya poda inayokuwa na collagen ya baharini, biotin, vitamini C, melatonin, na asidi ya hyaluronic kwa unyevu wa ngozi, msaada wa nywele/kucha, na kupunguza ukale.", desc_fr:"Complément alimentaire en poudre contenant du collagène marin, de la biotine, de la vitamine C, de la mélatonine et de l'acide hyaluronique pour l'élasticité de la peau, le soutien cheveux/ongles et l'anti-âge.", benefits_en:'["Marine collagen source","Contains biotin & vitamin C","Supports skin elasticity","Anti-aging formula"]', benefits_sw:'["Chanzo cha collagen ya baharini","Ina biotin na vitamini C","Kusaidia unyevu wa ngozi","Fomula ya kupunguza ukale"]', benefits_fr:'["Source de collagène marin","Contient biotine & vitamine C","Soutient l\'élasticité cutanée","Formule anti-âge"]', sort_order:4 },
  { name_en:"Multi Collagen Peptides Powder (1 lb / 454g)", name_sw:"Multi Collagen Peptides Powder (1 lb / 454g)", name_fr:"Poudre Multi Collagène Peptides (1 lb / 454g)", category:"supplements", price:2499, original_price:3500, unit_en:"454g powder", unit_sw:"Poda 454g", unit_fr:"454g poudre", image_url:"assets/photoz/IMG-20260721-WA0180.jpg", stock:20, rating:4.7, review_count:15, badges:[], desc_en:"Hydrolyzed multi-collagen types I, II, III, V, & X infused with biotin, vitamin C, and hyaluronic acid to promote joint, skin, hair, and nail health.", desc_sw:"Collagen ya aina nyingi iliyeyeyushwa I, II, III, V, na X iliyojumuishwa na biotin, vitamini C, na asidi ya hyaluronic ili kukuza afya ya viungo, ngozi, nywele, na kucha.", desc_fr:"Multi-collagène hydrolysé types I, II, III, V et X enrichi en biotine, vitamine C et acide hyaluronique pour promouvoir la santé des articulations, de la peau, des cheveux et des ongles.", benefits_en:'["Hydrolyzed multi-type collagen","Infused with biotin & vitamin C","Promotes joint & skin health","Supports hair & nail growth"]', benefits_sw:'["Collagen ya aina nyingi iliyeyeyushwa","Iliyojumuishwa na biotin na vitamini C","Kukuza afya ya viungo na ngozi","Kusaidia ukuaji wa nywele na kucha"]', benefits_fr:'["Collagène multi-types hydrolysé","Enrichi en biotine & vitamine C","Promeut la santé articulaire & cutanée","Soutient la croissance cheveux & ongles"]', sort_order:5 },
  { name_en:"Gluta Master Collagen Glowing Powder - Vanilla (1 kg)", name_sw:"Gluta Master Collagen Glowing Powder - Vanilla (1 kg)", name_fr:"Gluta Master Collagène Poudre Éclat - Vanille (1 kg)", category:"supplements", price:2899, original_price:5800, unit_en:"1 kg powder", unit_sw:"Poda 1 kg", unit_fr:"1 kg poudre", image_url:"assets/photoz/IMG-20260721-WA0183.jpg", stock:12, rating:4.8, review_count:11, badges:["Premium"], desc_en:"Vanilla-flavored collagen supplement powder containing bovine collagen peptides, glutathione, and vitamin C. Works from the inside out to brighten skin tone, fade fine lines, rebuild skin firmness, and strengthen hair and nails.", desc_sw:"Poda ya nyongeza ya collagen yenye ladha ya vanilla inayokuwa na collagen peptides za ng'ombe, glutathione, na vitamini C. Inafanya kazi kutoka ndani nje kuboresha rangi ya ngozi, kupunguza mistari miembamba, kujenga uthabiti wa ngozi, na kuimarisha nywele na kucha.", desc_fr:"Poudre de complément au collagène saveur vanille contenant des peptides de collagène bovin, du glutathion et de la vitamine C. Agit de l'intérieur pour éclaircir le teint, atténuer les rides fines, restaurer la fermeté cutanée et renforcer cheveux et ongles.", benefits_en:'["Vanilla-flavored collagen powder","Bovine collagen peptides & glutathione","Brightens skin tone","Strengthens hair & nails"]', benefits_sw:'["Poda ya collagen yenye ladha ya vanilla","Collagen peptides za ng\'ombe na glutathione","Kuboresha rangi ya ngozi","Kuimarisha nywele na kucha"]', benefits_fr:'["Poudre de collagène saveur vanille","Peptides de collagène bovin & glutathion","Éclaircit le teint","Renforce cheveux & ongles"]', sort_order:6 },
  { name_en:"5D Gluta Plant-Based Protein 100% Whey (1 kg)", name_sw:"5D Gluta Plant-Based Protein 100% Whey (1 kg)", name_fr:"5D Gluta Protéine Végétale 100% Whey (1 kg)", category:"supplements", price:1999, original_price:null, unit_en:"1 kg powder", unit_sw:"Poda 1 kg", unit_fr:"1 kg poudre", image_url:"assets/photoz/IMG-20260721-WA0184.jpg", stock:22, rating:4.5, review_count:8, badges:[], desc_en:"A 1kg dietary protein drink mix formula designed for daily nutrition, muscle recovery, and overall skin support.", desc_sw:"Fomula ya protini ya kunywa 1 kg iliyotengenezwa kwa lishe ya kila siku, urejeshaji wa misa, na msaada wa jumla wa ngozi.", desc_fr:"Formule de boisson protéinée diététique de 1 kg conçue pour la nutrition quotidienne, la récupération musculaire et le soutien cutané global.", benefits_en:'["100% whey protein","Supports muscle recovery","Daily nutrition formula","Skin support benefits"]', benefits_sw:'["Protini ya whey 100%","Kusaidia urejeshaji wa misa","Fomula ya lishe ya kila siku","Manufaa ya msaada wa ngozi"]', benefits_fr:'["100% protéine whey","Soutient la récupération musculaire","Formule nutrition quotidienne","Bienfaits de soutien cutané"]', sort_order:7 },
  { name_en:"Daynee Evening Primrose Oil Gummies (60s)", name_sw:"Daynee Evening Primrose Oil Gummies (Viatu 60)", name_fr:"Daynee Pastilles Huile d'Oe-nothère (60)", category:"supplements", price:1050, original_price:2280, unit_en:"60 gummies", unit_sw:"Viatu 60", unit_fr:"60 pastilles", image_url:"assets/photoz/IMG-20260721-WA0187.jpg", stock:20, rating:4.6, review_count:9, badges:[], desc_en:"Gummy supplements containing evening primrose oil to support hormonal balance, PMS relief, and healthy skin.", desc_sw:"Viatu vya nyongeza vinavyokuwa na mafuta ya evening primrose ili kusaidia usawa wa homoni, kupunguza PMS, na ngozi yenye afya.", desc_fr:"Pastilles complémentaires contenant de l'huile d'oe-nothère pour soutenir l'équilibre hormonal, le soulagement du syndrome prémenstruel et une peau saine.", benefits_en:'["Supports hormonal balance","PMS relief","Promotes healthy skin","Evening primrose oil enriched"]', benefits_sw:'["Kusaidia usawa wa homoni","Kupunguza PMS","Kukuza ngozi yenye afya","Iliyojumuishwa na mafuta ya evening primrose"]', benefits_fr:'["Soutient l\'équilibre hormonal","Soulage le SPMS","Favorise une peau saine","Enrichie en huile d\'oe-nothère"]', sort_order:8 },
  { name_en:"Daynee Calcium + D3 Gummies", name_sw:"Daynee Calcium + D3 Gummies", name_fr:"Daynee Pastilles Calcium + D3", category:"supplements", price:1350, original_price:2500, unit_en:"60 gummies", unit_sw:"Viatu 60", unit_fr:"60 pastilles", image_url:"assets/photoz/IMG-20260721-WA0188.jpg", stock:22, rating:4.7, review_count:12, badges:[], desc_en:"Dietary gummy supplements packed with calcium and vitamin D3 to promote strong bones, teeth, and immune function.", desc_sw:"Viatu vya nyongeza ya chakula vilivyojaa calcium na vitamini D3 ili kukuza mifupa imara, meno, na utendaji wa kinga.", desc_fr:"Pastilles complémentaires alimentaires riches en calcium et en vitamine D3 pour promouvoir des os, des dents et une fonction immunitaire solides.", benefits_en:'["Calcium & vitamin D3","Promotes strong bones & teeth","Supports immune function","Delicious gummy form"]', benefits_sw:'["Calcium na vitamini D3","Kukuza mifupa imara na meno","Kusaidia utendaji wa kinga","Fomula ya viatu ladha"]', benefits_fr:'["Calcium & vitamine D3","Favorise os & dents solides","Soutient la fonction immunitaire","Forme de pastille délicieuse"]', sort_order:9 },
  { name_en:"Daynee Magnesium Glycinate Gummies (60s, 600mg)", name_sw:"Daynee Magnesium Glycinate Gummies (Viatu 60, 600mg)", name_fr:"Daynee Pastilles Magnésium Glycinate (60, 600mg)", category:"supplements", price:1099, original_price:2200, unit_en:"60 gummies, 600mg", unit_sw:"Viatu 60, 600mg", unit_fr:"60 pastilles, 600mg", image_url:"assets/photoz/IMG-20260721-WA0189.jpg", stock:20, rating:4.8, review_count:14, badges:["Popular"], desc_en:"High-absorption magnesium complex gummies formulated to promote calm and relaxation, improve sleep, and support muscle, joint, and bone health.", desc_sw:"Viatu vya magnesium complex vinavyokunywa vizuri vilivyotengenezwa kukuza upole na upumziko, kuboresha usingizi, na kuunga mkono afya ya misa, viungo, na mifupa.", desc_fr:"Pastilles de complexe magnésium à haute absorption formulées pour promouvoir le calme et la relaxation, améliorer le sommeil et soutenir la santé musculaire, articulaire et osseuse.", benefits_en:'["High-absorption magnesium glycinate","Promotes calm & relaxation","Improves sleep quality","Supports muscle & bone health"]', benefits_sw:'["Magnesium glycinate inayokunywa vizuri","Kukuza upole na upumziko","Kuboresha ubora wa usingizi","Kusaidia afya ya misa na mifupa"]', benefits_fr:'["Magnésium glycinate à haute absorption","Favorise calme & relaxation","Améliore la qualité du sommeil","Soutient santé musculaire & osseuse"]', sort_order:10 },
  { name_en:"Daynee Vitamin C Gummies (60s, 250mg)", name_sw:"Daynee Vitamin C Gummies (Viatu 60, 250mg)", name_fr:"Daynee Pastilles Vitamine C (60, 250mg)", category:"supplements", price:1450, original_price:2200, unit_en:"60 gummies, 250mg", unit_sw:"Viatu 60, 250mg", unit_fr:"60 pastilles, 250mg", image_url:"assets/photoz/IMG-20260721-WA0192.jpg", stock:25, rating:4.7, review_count:16, badges:[], desc_en:"Vegan gummy supplements high in Vitamin C to support immune system health, provide antioxidant protection, and boost iron absorption.", desc_sw:"Viatu vya mboga vinavyokuwa na Vitamini C nyingi ili kusaidia afya ya mfumo wa kinga, kutoa ulinzi wa antioxidants, na kuongeza uchukuaji wa chuma.", desc_fr:"Pastilles véganes riches en vitamine C pour soutenir la santé immunitaire, fournir une protection antioxydante et améliorer l'absorption du fer.", benefits_en:'["High vitamin C content","Vegan-friendly formula","Immune system support","Boosts iron absorption"]', benefits_sw:'["Maudhui ya vitamini C ya juu","Fomula rafiki kwa mboga","Msaada wa mfumo wa kinga","Kuongeza uchukuaji wa chuma"]', benefits_fr:'["Riche en vitamine C","Formule végane","Soutien du système immunitaire","Améliore l\'absorption du fer"]', sort_order:11 },
  { name_en:"Jiake Ultimate Maca Protein Powder (300g)", name_sw:"Jiake Ultimate Maca Protein Powder (300g)", name_fr:"Jiake Poudre Protéinée Maca Ultime (300g)", category:"supplements", price:4275, original_price:null, unit_en:"300g powder", unit_sw:"Poda 300g", unit_fr:"300g poudre", image_url:"assets/photoz/IMG-20260721-WA0195.jpg", stock:10, rating:4.5, review_count:6, badges:[], desc_en:"High-potency 15:1 concentrate formula blending maca root, aguaje, fenugreek, tribulus, and dong quai designed to promote hip and curve enhancement.", desc_sw:"Fomula ya mkusanyiko 15:1 yenye nguvu kubwa inayochanganya mizizi ya maca, aguaje, alfalfa, tribulus, na dong quai iliyotengenezwa kukuza urekebishaji wa viuno na mikunjo.", desc_fr:"Formule concentrée 15:1 haute puissance mélangeant racine de maca, aguaje, fenugrec, tribulus et dong quai conçue pour favoriser l'amélioration des hanches et des courbes.", benefits_en:'["15:1 concentrate formula","Maca root blend","Promotes body contouring","Natural herbal ingredients"]', benefits_sw:'["Fomula ya mkusanyiko 15:1","Mchanganyiko wa mizizi ya maca","Kukuza urekebishaji wa mwili","Viungo vya mimea asili"]', benefits_fr:'["Formule concentrée 15:1","Mélange racine de maca","Favorise la silhouette","Ingrédients à base de plantes"]', sort_order:12 },
  { name_en:"WinsTown / Daynee Assorted Health Gummies (Display Set)", name_sw:"WinsTown / Daynee Assorted Health Gummies (Set ya Kuonyesha)", name_fr:"WinsTown / Daynee Pastilles Santé Assorties (Ensemble)", category:"supplements", price:1550, original_price:2200, unit_en:"Per bottle", unit_sw:"Kwa chupa", unit_fr:"Par bouteille", image_url:"assets/photoz/IMG-20260721-WA0197.jpg", stock:30, rating:4.6, review_count:8, badges:["New"], desc_en:"A wide variety display of specialized 60-gummy dietary supplements including Sea Moss, Keto+ACV, Probiotics, BBL Gummies, and Glutathione Whitening.", desc_sw:"Onyesho la aina mbalimbali za viatu vya nyongeza ya chakula vya vidonge 60 ikiwa ni pamoja na Sea Moss, Keto+ACV, Probiotics, BBL Gummies, na Glutathione Whitening.", desc_fr:"Large variété de compléments alimentaires en pastilles spécialisées de 60 incluant Sea Moss, Keto+ACV, Probiotiques, BBL Pastilles et Glutathion Éclaircissant.", benefits_en:'["Multiple supplement varieties","Sea Moss, Keto+ACV, Probiotics","BBL & Glutathione options","60 gummies per bottle"]', benefits_sw:'["Aina nyingi za nyongeza","Sea Moss, Keto+ACV, Probiotics","Chaguzi za BBL na Glutathione","Viatu 60 kwa chupa"]', benefits_fr:'["Variétés de compléments multiples","Sea Moss, Keto+ACV, Probiotiques","Options BBL & Glutathion","60 pastilles par bouteille"]', sort_order:13 },
  { name_en:"MTM-100 Sildenafil Citrate Tablets (100mg, 4s)", name_sw:"MTM-100 Sildenafil Citrate Tablets (100mg, Vidonge 4)", name_fr:"MTM-100 Comprimés Citrate de Sildénafil (100mg, 4)", category:"supplements", price:500, original_price:null, unit_en:"4 tablets", unit_sw:"Vidonge 4", unit_fr:"4 comprimés", image_url:"assets/photoz/IMG-20260721-WA0198.jpg", stock:40, rating:4.4, review_count:20, badges:[], desc_en:"Oral prescription tablet blister pack (4s) indicated for the treatment and management of erectile dysfunction.", desc_sw:"Vidonge vya dawa ya mdomo (vidonge 4) vinavyotumika kutibu na kusimamia matatizo ya upenyezaji.", desc_fr:"Plaquette de comprimés oraux sur ordonnance (4s) indiqués pour le traitement et la gestion de la dysfonction érectile.", benefits_en:'["100mg sildenafil citrate","Treatment for erectile dysfunction","4-tablet blister pack","Prescription medication"]', benefits_sw:'["Sildenafil citrate 100mg","Dawa ya kutibu matatizo ya upenyezaji","Kifurushi cha vidonge 4","Dawa ya daktari"]', benefits_fr:'["Citrate de sildénafil 100mg","Traitement de la dysfonction érectile","Plaquette de 4 comprimés","Médicament sur ordonnance"]', sort_order:14 },

  // ===== Skincare =====
  { name_en:"CeraVe Moisturising Cream (16 oz / 454 g)", name_sw:"CeraVe Cream ya Kupaka (16 oz / 454 g)", name_fr:"Crème Hydratante CeraVe (16 oz / 454 g)", category:"skincare", price:2099, original_price:3650, unit_en:"454g tub", unit_sw:"Chupa 454g", unit_fr:"Pot 454g", image_url:"assets/photoz/IMG-20260721-WA0155.jpg", stock:15, rating:4.9, review_count:25, badges:["Bestseller"], desc_en:"Dermatologist-developed moisturizing cream for dry to very dry skin. Powered by 3 essential ceramides, hyaluronic acid, and MVE continuous-release technology, it restores the skin's natural barrier and provides 24-hour hydration for face and body.", desc_sw:"Cream ya kuporesha iliyotengenezwa na daktari wa ngozi kwa ngozi kavu hadi kavu sana. Inaendeshwa na ceramide 3 muhimu, asidi ya hyaluronic, na teknolojia ya MVE ya kuachilia endelevu, inarejesha kikomo cha asili cha ngozi na inatoa unyevu wa masaa 24 kwa uso na mwili.", desc_fr:"Crème hydratante développée par des dermatologues pour les peaux sèches à très sèches. Alimentée par 3 céramides essentiels, l'acide hyaluronique et la technologie à libération continue MVE, elle restaure la barrière naturelle de la peau et offre une hydratation de 24 heures pour le visage et le corps.", benefits_en:'["3 essential ceramides","Hyaluronic acid & MVE technology","24-hour hydration","For face & body"]', benefits_sw:'["Ceramide 3 muhimu","Asidi ya hyaluronic na teknolojia ya MVE","Unyevu wa masaa 24","Kwa uso na mwili"]', benefits_fr:'["3 céramides essentiels","Acide hyaluronique & technologie MVE","Hydratation 24 heures","Pour le visage & le corps"]', sort_order:15 },
  { name_en:"Osckal Alpha Arbutin 3 Plus Whitening Body Soap", name_sw:"Osckal Alpha Arbutin 3 Plus Whitening Body Soap", name_fr:"Savon Corporel Osckal Alpha Arbutin 3 Plus Éclaircissant", category:"skincare", price:1350, original_price:1500, unit_en:"Body soap", unit_sw:"Sabuni ya mwili", unit_fr:"Savon corporel", image_url:"assets/photoz/IMG-20260721-WA0178.jpg", stock:25, rating:4.5, review_count:10, badges:[], desc_en:"A body soap formulated with alpha arbutin to target dark spots, hyperpigmentation, and uneven skin tone while providing hydration and anti-aging benefits.", desc_sw:"Sabuni ya mwili iliyotengenezwa na alpha arbutin kulenga mafundo meusi, hyperpigmentation, na rangi isiyofautika ya ngozi huku ikitoa unyevu na manufaa ya kupunguza ukale.", desc_fr:"Savon corporel formulé avec l'alpha arbutin pour cerner les taches sombres, l'hyperpigmentation et le teint inégal tout en offrant hydratation et bienfaits anti-âge.", benefits_en:'["Alpha arbutin formula","Targets dark spots","Anti-aging benefits","Hydrating body soap"]', benefits_sw:'["Fomula ya alpha arbutin","Inalenga mafundo meusi","Manufaa ya kupunguza ukale","Sabuni ya mwili yenye unyevu"]', benefits_fr:'["Formule alpha arbutin","Cible les taches sombres","Bienfaits anti-âge","Savon corporel hydratant"]', sort_order:16 },
  { name_en:"Sadoer Tea Tree Acnes Oil Control Face Cream", name_sw:"Sadoer Tea Tree Acnes Oil Control Face Cream", name_fr:"Crème Visage Sadoer Tea Tree Acnes Contrôle de Sébum", category:"skincare", price:489, original_price:null, unit_en:"Face cream", unit_sw:"Cream ya uso", unit_fr:"Crème pour le visage", image_url:"assets/photoz/IMG-20260721-WA0185.jpg", stock:30, rating:4.4, review_count:8, badges:[], desc_en:"A gentle facial cream with tea tree extract designed to balance oil secretion, reduce acne marks, and lock in moisture.", desc_sw:"Cream laini ya uso yenye extract ya tea tree iliyotengenezwa kusawazisha utengenezaji wa mafuta, kupunguza alama za chunusi, na kufunga unyevu.", desc_fr:"Crème faciale douce avec extrait de tea tree conçue pour équilibrer la sécrétion de sébum, réduire les traces d'acné et fixer l'hydratation.", benefits_en:'["Tea tree extract","Controls oil secretion","Reduces acne marks","Locks in moisture"]', benefits_sw:'["Extract ya tea tree","Kusawazisha utengenezaji wa mafuta","Kupunguza alama za chunusi","Kufunga unyevu"]', benefits_fr:'["Extrait de tea tree","Équilibre la sécrétion de sébum","Réduit les traces d\'acné","Fixe l\'hydratation"]', sort_order:17 },
  { name_en:"Dr. Meinaier Vitamin C & Pure Collagen Sugar Scrub (650g)", name_sw:"Dr. Meinaier Vitamin C & Pure Collagen Sugar Scrub (650g)", name_fr:"Gommage Sucre Dr. Meinaier Vitamine C & Collagène Pur (650g)", category:"skincare", price:499, original_price:1200, unit_en:"650g scrub", unit_sw:"Scrub 650g", unit_fr:"650g gommage", image_url:"assets/photoz/IMG-20260721-WA0191.jpg", stock:18, rating:4.6, review_count:11, badges:[], desc_en:"An exfoliating body sugar scrub containing Vitamin C and Collagen designed to brighten skin tone, fade dark spots, and deeply hydrate.", desc_sw:"Scrub ya sukari ya mwili inayosafisha ikijumuisha Vitamini C na Collagen iliyotengenezwa kuboresha rangi ya ngozi, kupunguza mafundo meusi, na kuweka unyevu wa kina.", desc_fr:"Gommage corporel au sucre contenant de la vitamine C et du collagène conçu pour éclaircir le teint, atténuer les taches sombres et hydrater en profondeur.", benefits_en:'["Vitamin C & collagen enriched","Exfoliating sugar scrub","Brightens skin tone","Deep hydration"]', benefits_sw:'["Iliyojumuishwa na Vitamini C na Collagen","Scrub ya sukari inayosafisha","Kuboresha rangi ya ngozi","Unyevu wa kina"]', benefits_fr:'["Enrichie vitamine C & collagène","Gommage sucré exfoliant","Éclaircit le teint","Hydratation profonde"]', sort_order:18 },

  // ===== Body Care =====
  { name_en:"Dove Exfoliating Body Polish / Body Scrub", name_sw:"Dove Exfoliating Body Polish / Body Scrub", name_fr:"Dove Polish Corporel Exfoliant / Gommage Corporel", category:"bodycare", price:1049, original_price:1850, unit_en:"Body scrub", unit_sw:"Scrub ya mwili", unit_fr:"Gommage corporel", image_url:"assets/photoz/IMG-20260721-WA0156.jpg", stock:20, rating:4.7, review_count:14, badges:["Popular"], desc_en:"Gentle exfoliating scrub featuring Dove's signature ¼ moisturizing cream formula. Formulated with botanical extracts like Himalayan Salt & Rose Oil or Pomegranate Seeds & Shea Butter to buff away dead skin cells and reveal smooth, radiant skin.", desc_sw:"Scrub laini inayo safisha ikijumuisha fomula ya Dove ya ¼ ya cream ya kuporesha. Imetengenezwa na extract za mimea kama vile Chumvi ya Himalayan na Mafuta ya Waridi au Mbegu za Pomegranate na Shea Butter kuondoa seli zilizokufa na kuonyesha ngozi laini, inayong'aa.", desc_fr:"Gommage exfoliant doux avec la formule signature ¼ crème hydratante de Dove. Formulé avec des extraits botaniques comme le sel himalayen et l'huile de rose ou les graines de grenade et le beurre de karité pour éliminer les cellules mortes et révéler une peau lisse et éclatante.", benefits_en:'["¼ moisturizing cream formula","Botanical extracts","Buff away dead skin cells","Smooth, radiant skin"]', benefits_sw:'["Fomula ya ¼ cream ya kuporesha","Extract za mimea","Kuondoa seli zilizokufa","Ngozi laini, inayong\'aa"]', benefits_fr:'["Formule ¼ crème hydratante","Extraits botaniques","Élimine les cellules mortes","Peau lisse et éclatante"]', sort_order:19 },
  { name_en:"Kormesic 100% Raw Batana Oil", name_sw:"Kormesic 100% Raw Batana Oil", name_fr:"Kormesic Huile de Batana brute 100%", category:"bodycare", price:350, original_price:null, unit_en:"Hair oil", unit_sw:"Mafuta ya nywele", unit_fr:"Huile pour cheveux", image_url:"assets/photoz/IMG-20260721-WA0181.jpg", stock:35, rating:4.5, review_count:7, badges:[], desc_en:"Raw, unrefined batana oil focused on stimulating hair growth, strengthening strands, activating hair follicles, and repairing damage.", desc_sw:"Mafuta ya batana ghafi, isiyosindikwa, iliyolengwa kuchochea ukuaji wa nywele, kuimarisha nyuzi, kuwasha follicles za nywele, na kurekebisha uharibifu.", desc_fr:"Huile de batana brute, non raffinée, conçue pour stimuler la pousse des cheveux, renforcer les mèches, activer les follicules pileux et réparer les dommages.", benefits_en:'["100% raw & unrefined","Stimulates hair growth","Strengthens hair strands","Repairs hair damage"]', benefits_sw:'["100% ghafi na isiyosindikwa","Kuchochea ukuaji wa nywele","Kuimarisha nyuzi za nywele","Kurekebisha uharibifu wa nywele"]', benefits_fr:'["100% brute & non raffinée","Stimule la pousse des cheveux","Renforce les mèches","Répare les dommages capillaires"]', sort_order:20 },
  { name_en:"Best Collagen Serum Body Oil (Yellow)", name_sw:"Best Collagen Serum Body Oil (Njano)", name_fr:"Huile Corporelle Sérum Collagène Best (Jaune)", category:"bodycare", price:1250, original_price:1800, unit_en:"Body oil serum", unit_sw:"Sérum ya mafuta ya mwili", unit_fr:"Sérum huile corporelle", image_url:"assets/photoz/IMG-20260721-WA0193.jpg", stock:18, rating:4.6, review_count:9, badges:[], desc_en:"A collagen-enriched body serum formulated with Vitamin D to deeply hydrate, repair sun damage, reduce fine lines, and improve skin barrier elasticity.", desc_sw:"Sérum ya mwili iliyojumuishwa na collagen iliyotengenezwa na Vitamini D kuweka unyevu wa kina, kurekebisha uharibifu wa jua, kupunguza mistari miembamba, na kuboresha unyevu wa kikomo cha ngozi.", desc_fr:"Sérum corporel enrichi au collagène formulé avec la vitamine D pour hydrater en profondeur, réparer les dommages solaires, réduire les rides fines et améliorer l'élasticité de la barrière cutanée.", benefits_en:'["Collagen-enriched serum","Vitamin D formula","Deep hydration & repair","Reduces fine lines"]', benefits_sw:'["Sérum iliyojumuishwa na collagen","Fomula ya Vitamini D","Unyevu wa kina na ukarabati","Kupunguza mistari miembamba"]', benefits_fr:'["Sérum enrichi au collagène","Formule Vitamine D","Hydratation & réparation profondes","Réduit les rides fines"]', sort_order:21 },
  { name_en:"Best Collagen White Body Oil Extra Whitening (Pink, 500ml)", name_sw:"Best Collagen White Body Oil Extra Whitening (Waridi, 500ml)", name_fr:"Huile Corporelle Blanche Collagène Best Extra Éclaircissante (Rose, 500ml)", category:"bodycare", price:1250, original_price:1800, unit_en:"500ml body oil", unit_sw:"Mafuta ya mwili 500ml", unit_fr:"500ml huile corporelle", image_url:"assets/photoz/IMG-20260721-WA0194.jpg", stock:18, rating:4.5, review_count:7, badges:[], desc_en:"An extra-strong body oil serum infused with Vitamin D designed to target dark spots, brighten the complexion, and tone skin texture.", desc_sw:"Sérum ya mafuta ya mwili iliyoimarishwa iliyojumuishwa na Vitamini D iliyotengenezwa kulenga mafundo meusi, kuboresha rangi ya ngozi, na kusawazisha muundo wa ngozi.", desc_fr:"Sérum huile corporelle extra-fort enrichi en vitamine D conçu pour cerner les taches sombres, éclaircir le teint et tonifier la texture de la peau.", benefits_en:'["Extra-strength formula","Vitamin D infused","Targets dark spots","Tones skin texture"]', benefits_sw:'["Fomula iliyoimarishwa","Iliyojumuishwa na Vitamini D","Inalenga mafundo meusi","Kusawazisha muundo wa ngozi"]', benefits_fr:'["Formule extra-forte","Enrichie vitamine D","Cible les taches sombres","Tonifie la texture cutanée"]', sort_order:22 },

  // ===== Wellness =====
  { name_en:"Sajed Mamool Incense (100 g)", name_sw:"Sajed Mamool Incense (100 g)", name_fr:"Encens Sajed Mamool (100 g)", category:"wellness", price:850, original_price:1200, unit_en:"100g incense", unit_sw:"Ungo 100g", unit_fr:"100g encens", image_url:"assets/photoz/IMG-20260721-WA0172.jpg", stock:20, rating:4.6, review_count:8, badges:[], desc_en:"Traditional Middle Eastern bakhoor incense tablets crafted with floral and woody aromatic notes. Designed for charcoal or electric burners to disperse long-lasting, rich scents through living spaces, prayer areas, and garments.", desc_sw:"Vidonge vya ungo wa bakhoor wa jadi wa Mashariki ya Kati vilivyotengenezwa kwa alama za harufu za ua na mbao. Vilivyoundwa kwa mashabaha ya makaa au umeme kusambaza harufu ndefu, tajiri katika nafasi zaishi, maeneo ya kuombea, na nguo.", desc_fr:"Tablettes d'encens bakhoor traditionnel du Moyen-Orient élaborées avec des notes aromatiques florales et boisées. Conçues pour les brûleurs à charbon ou électriques pour diffuser des parfums riches et durables dans les espaces de vie, les zones de prière et les vêtements.", benefits_en:'["Traditional Middle Eastern bakhoor","Floral & woody notes","Long-lasting fragrance","For living spaces & garments"]', benefits_sw:'["Bakhoor ya jadi ya Mashariki ya Kati","Alama za ua na mbao","Harufu ndefu","Kwa nafasi zaishi na nguo"]', benefits_fr:'["Bakhoor traditionnel moyen-oriental","Notes florales & boisées","Parfum durable","Pour espaces & vêtements"]', sort_order:23 },
  { name_en:"WinsTown Slim Plus Fat Burner (60 Capsules)", name_sw:"WinsTown Slim Plus Fat Burner (Vidonge 60)", name_fr:"WinsTown Slim Plus Brûleur de Graisse (60 Gélules)", category:"wellness", price:1550, original_price:1800, unit_en:"60 capsules", unit_sw:"Vidonge 60", unit_fr:"60 gélules", image_url:"assets/photoz/IMG-20260721-WA0182.jpg", stock:22, rating:4.5, review_count:10, badges:[], desc_en:"A 60-capsule healthy detox dietary supplement designed to boost metabolism, aid in fat breakdown, and suppress appetite.", desc_sw:"Nyongeza ya chakula ya afya ya vidonge 60 iliyotengenezwa kuongeza metabolismi, kusaidia uvunjaji wa mafuta, na kuzuia hamu ya kula.", desc_fr:"Complément alimentaire détox sain en 60 gélules conçu pour booster le métabolisme, aider à la décomposition des graisses et supprimer l'appétit.", benefits_en:'["60-capsule detox formula","Boosts metabolism","Aids fat breakdown","Suppresses appetite"]', benefits_sw:'["Fomula ya detox ya vidonge 60","Kuongeza metabolismi","Kusaidia uvunjaji wa mafuta","Kuzuia hamu ya kula"]', benefits_fr:'["Formule détox 60 gélules","Booster le métabolisme","Aide à la décomposition des graisses","Supprime l\'appétit"]', sort_order:24 },
];

const promos = [
  { code:'WELCOME10', type:'percent', value:10, category:null, description:'10% off your order', min_order:0, max_uses:100 },
  { code:'BEAUTY20', type:'category', value:20, category:'skincare', description:'20% off skincare products', min_order:0, max_uses:100 },
  { code:'FREESHIP', type:'freeship', value:0, category:null, description:'Free shipping', min_order:0, max_uses:200 },
  { code:'SUPPLE15', type:'category', value:15, category:'supplements', description:'15% off supplements', min_order:0, max_uses:100 },
];

function escape(str) {
  return String(str).replace(/'/g, "''");
}

function buildProductSQL(p) {
  return `INSERT INTO products (name_en, name_sw, name_fr, category, price, original_price, unit_en, unit_sw, unit_fr, image_url, stock, rating, review_count, badges, desc_en, desc_sw, desc_fr, benefits_en, benefits_sw, benefits_fr, sort_order) VALUES ('${escape(p.name_en)}', '${escape(p.name_sw)}', '${escape(p.name_fr)}', '${escape(p.category)}', ${p.price}, ${p.original_price || 'NULL'}, '${escape(p.unit_en)}', '${escape(p.unit_sw)}', '${escape(p.unit_fr)}', '${escape(p.image_url)}', ${p.stock}, ${p.rating}, ${p.review_count}, '${escape(JSON.stringify(p.badges))}', '${escape(p.desc_en)}', '${escape(p.desc_sw)}', '${escape(p.desc_fr)}', '${escape(p.benefits_en)}', '${escape(p.benefits_sw)}', '${escape(p.benefits_fr)}', ${p.sort_order});`;
}

function buildPromoSQL(p) {
  return `INSERT INTO promos (code, type, value, category, description, min_order, max_uses) VALUES ('${escape(p.code)}', '${escape(p.type)}', ${p.value}, ${p.category ? `'${escape(p.category)}'` : 'NULL'}, '${escape(p.description)}', ${p.min_order}, ${p.max_uses});`;
}

// Build the full SQL
let sql = '-- U-NiceNutraCare Seed Data\n-- Generated by seed.js\n\n';

sql += '-- Products\n';
products.forEach(p => { sql += buildProductSQL(p) + '\n'; });

sql += '\n-- Promo Codes\n';
promos.forEach(p => { sql += buildPromoSQL(p) + '\n'; });

// Write to file
fs.writeFileSync('seed-data.sql', sql);
console.log('Generated seed-data.sql with ' + products.length + ' products and ' + promos.length + ' promos');
console.log('\nTo seed your D1 database, run:');
console.log('  wrangler d1 execute unicenutra-db --file=./schema.sql');
console.log('  wrangler d1 execute unicenutra-db --file=./seed-data.sql');
